Repository explosion/weasel, pull requests merged in 2023-07, with the labels that each got.

#39 Fix mypy pre-commit run
  .pre-commit-config.yaml
Labels: bug, tests

#38 fix entry point definition
  .github/workflows/tests.yml
  setup.cfg
Labels: bug

#42 Accept both SPACY PROJECT and WEASEL in markers
  weasel/cli/document.py
  weasel/tests/cli/test_document.py
Labels: bug, enhancement

#47 Fix error code E501
  weasel/util/commands.py
Labels: bug

#43 Switch from pathy to cloudpathlib
  requirements.txt
  setup.cfg
  weasel/cli/remote_storage.py
  weasel/tests/cli/test_document.py
  weasel/util/filesystem.py
  weasel/util/remote.py
Labels: enhancement
